# ubuntu
ubuntu_php7_ppa_repo: "ppa:ondrej/php"

apt_php_packages:
  - "{{ apt_php_version }}"
  - "{{ apt_php_version }}-json"
  - "{{ apt_php_version }}-fpm"
  - "{{ apt_php_version }}-common"
  - "{{ apt_php_version }}-opcache"
  - "{{ apt_php_version }}-cli"
  - "{{ apt_php_version }}-bcmath"
  - "{{ apt_php_version }}-ldap"
  - "{{ apt_php_version }}-cgi"
  - "{{ apt_php_version }}-mbstring"
  - "{{ apt_php_version }}-mcrypt"
  - "{{ apt_php_version }}-mysqlnd"
  - "{{ apt_php_version }}-pdo"
  - "{{ apt_php_version }}-imagick"
  - "{{ apt_php_version }}-memcached"
  - "{{ apt_php_version }}-redis"
  - "{{ apt_php_version }}-soap"
  - "{{ apt_php_version }}-xml"
  - "{{ apt_php_version }}-xmlrpc"
  - "{{ apt_php_version }}-dev"
  - "{{ apt_php_version }}-pdo-dblib"
  - "{{ apt_php_version }}-zip"
  - "{{ apt_php_version }}-gmp"

# centos 7
yum_php_packages:
  - "{{ yum_php_version }}"
  - "{{ yum_php_version }}-json"
  - "{{ yum_php_version }}-fpm"
  - "{{ yum_php_version }}-common"
  - "{{ yum_php_version }}-opcache"
  - "{{ yum_php_version }}-cli"
  - "{{ yum_php_version }}-bcmath"
  - "{{ yum_php_version }}-ldap"
  - "{{ yum_php_version }}-cgi"
  - "{{ yum_php_version }}-mbstring"
  - "{{ yum_php_version }}-mcrypt"
  - "{{ yum_php_version }}-mysqlnd"
  - "{{ yum_php_version }}-pdo"
  - "{{ yum_php_version }}-imagick"
  - "{{ yum_php_version }}-memcached"
  - "{{ yum_php_version }}-redis"
  - "{{ yum_php_version }}-soap"
  - "{{ yum_php_version }}-xml"
  - "{{ yum_php_version }}-xmlrpc"
  - "{{ yum_php_version }}-pdo-dblib"
  - "{{ yum_php_version }}-pecl-zip"
  - "{{ yum_php_version }}-gmp"
  - "{{ yum_php_version }}-openssl"
  - "{{ yum_php_version }}-ctype"
  - "{{ yum_php_version }}-nette-tokenizer"
