ubuntu_php7_ppa_repo: "ppa:ondrej/php"

apt_php_packages:
  - php{{ php_version }}
  - php{{ php_version }}-json
  - php{{ php_version }}-fpm
  - php{{ php_version }}-common
  - php{{ php_version }}-opcache
  - php{{ php_version }}-cli
  - php{{ php_version }}-bcmath
  - php{{ php_version }}-ldap
  - php{{ php_version }}-cgi
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-mcrypt
  - php{{ php_version }}-mysqlnd
  - php{{ php_version }}-pdo
  - php{{ php_version }}-imagick
  - php{{ php_version }}-memcached
  - php{{ php_version }}-redis
  - php{{ php_version }}-soap
  - php{{ php_version }}-xml
  - php{{ php_version }}-xmlrpc
  - php{{ php_version }}-dev
  - php{{ php_version }}-pdo-dblib
  - php{{ php_version }}-gmp
  - php{{ php_version }}-zip