- name: Install Java11 packages
  yum:
    name: java-11-openjdk
    state: present

- name: Add Elasticsearch apt key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository
  template:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch-6.x.repo

- name: Install Filebeat
  yum:
    name: filebeat
    state: present

- name: Change elasticsearch.yml
  template:
    src: "filebeat.yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    mode: 0660
  notify:
    - restarted filebeat on centos
