- name: Install MariaDB apt dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_nested:
    "{{ mariadb_apt_dependencies }}"

- name: Add repository key to the system
  apt_key:
    keyserver: "{{ mariadb_repo_key }}"
    id: "{{ mariadb_repo_id }}"
    state: present

- name: Install MySQL-python pip package
  pip:
    name: "{{ item }}"
    state: present
  with_items: '{{ mariadb_pip_dependencies }}'

- name: Install MariaDB repository
  apt_repository:
    repo: "{{ ubuntu_mariadb_repo }}"
  when:
    ansible_distribution|lower == "ubuntu"

- name: Update and upgrade apt packages
  apt:
    force_apt_get: yes
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install mariadb server apt packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    "{{mariadb_packages}}"
  when:
      mariadb_packages is defined
  notify:
    - restarted mariadb

- name: Update mariadb root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    state: present
  with_items:
    - "{{ mariadb_default_hosts }}"

# TODO
- name: Create a new database with name 'homestead'
  mysql_db:
    name: "{{ mysql_database }}"
    state: present

# TODO
- name: Create a new user with name 'master' password 'password'
  mysql_db:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    state: present

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
  notify:
    - restarted mariadb

