- name: restarted mariadb
  service:
    name: '{{ mariadb_service }}'
    state: restarted
    enabled: yes

- name: reloaded mariadb
  service:
    name: '{{ mariadb_service }}'
    state: reloaded
    enabled: yes