- name: install web server
  apt:
    name: nginx
    state: latest
  when: ansible_distribution == 'Ubuntu'
  
- name: install web server
  yum:
    name: nginx
    state: latest
  when: 
    ansible_distribution == 'CentOS' and 
    ansible_distribution_major_version == '7'
