- name: install web server
  apt:
    name: nginx
    state: latest
  when: ansible_distribution == 'Ubuntu'
  
- name: install web server
  yum:
    name: nginx
    state: latest
  when:
    ansible_distribution == 'CentOS' and 
    ansible_distribution_major_version == '7'

- name: delete conf
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ delete_conf }}"
  when:
    delete_conf is defined

- name: copy nginx vhost and backup the original
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: "{{ item.backup }}"
  with_items:
    - "{{ copy_conf }}"
  when:
    copy_conf is defined