- name: Install web server
  apt:
    name: nginx
    state: latest
  when:
    ansible_distribution == 'Ubuntu'
  notify:
    - restarted nginx

- name: delete conf
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ delete_conf }}"
  when:
    delete_conf is defined

- name: copy_conf
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: "0755"
    backup: "yes"

- name: create folder_directory
  file:
    path:  "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode:  "{{ item.mode }}"
    state:  "{{ item.state }}"
  with_items:
    "{{ folder_directory }}"
  when:
    folder_directory is defined

- name: generate SSL_certificate
  command:
    openssl req -nodes -new -x509 -keyout {{ nginx_ssl_certificate_key }} -out {{ nginx_ssl_certificate }} -subj "{{ nginx_ssl_certificate_subject }}" -days {{ nginx_ssl_certificate_days }}
  args:
    creates: "{{ nginx_ssl_certificate }}"

- name: copy nginx vhost
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: "{{ item.backup }}"
  with_items:
    - "{{ nginx_vhost }}"
  when:
    nginx_vhost is defined

- name: copy index_php
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: "{{ item.backup }}"
  with_items:
    - "{{ index_php }}"
  when:
    index_php is defined