---
- name: Check if GitLab-CE is not Install
  stat:
    path: /usr/bin/gitlab-ctl
  register: gitlab_ctl

#- name: Check if GitLab-CE is already installed
#  stat:
#    path: /etc/gitlab

#- name: Update and upgrade apt packages
#  apt:
#    force_apt_get: yescurl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
#    upgrade: yes
#    update_cache: yes
#    cache_valid_time: 86400

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    "{{ apt_packages }}"
  when:
    apt_packages is defined

#- name: Add GitLab-EE apt key
#  apt_key:
#    url: https://packages.gitlab.com/gpg.key
#    state: present

#- name: Add GitLab-EE repository
#  apt_repository:
#    repo: "{{ item }}"
#    state: present
#  with_nested:
#    "{{ gitlab_apt_repos }}"
#  when:
#    gitlab_apt_repos is defined

#- name: Download GitLab-EE repository
#  get_url:
#    url: 'https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh'
#    dest: /tmp/gitlab-ee.deb.sh

- name: Install GitLab-CE
  shell: "curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash"
  when: gitlab_ctl.stat.exists == False

#- name: Execute GitLab-EE Deb script
#  command: /bin/bash /tmp/gitlab-ee.deb.sh

- name: Install GitLab-CE
  apt:
    name: gitlab-ce
    state: present

#- name: reconfigure gitlab-ctl
#  command: gitlab-ctl reconfigure

#- name: Change gitlab.rb
#  template:
#    src: "gitlab.rb.j2"
#    dest: "/etc/gitlab/gitlab.rb"
#    owner: root
#    mode: 0600

#- name: initialize gitlab configuration and directory
#  shell: gitlab-ctl reconfigure
#  when:
#    gitlab_rb_config.stat.exists == True