---
- name: Install requires package for yum module
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libselinux-python
    - epel-release

- name: Install remi repo
  yum:
    name: https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el7/gitlab-ce-11.3.0-ce.0.el7.x86_64.rpm
    state: present
  when:
    ansible_distribution == 'CentOS' and
    ansible_distribution_major_version == '7'

- name: Install yum-utils packages
  yum:
    name: yum-utils
    state: present
