mysql_port: "3306"
mysql_bind_address: "0.0.0.0"

# root
mysql_root_home: "/root"
mysql_root_name: "root"
mysql_root_password: "password"

# user
mysql_user_home: "~/"
mysql_user_name: "master"
mysql_user_password: "secret"

mysql_database:
  - name: homestead
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
    replicate: yes
  - name: example
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
    replicate: no

mysql_users:
  - name: master
    pass: password
    priv: "*.*:ALL"

mysql_repl_users:
  - name: repl
    pass: password
    priv: "*.*:ALL"

# Hosts
mysql_default_hosts:
  - 127.0.0.1
  - ::1
  - localhost

# This password is not secure! Please define your own password!
mariadb_admin_password:  "{{ ansible_machine_id | hash('sha1') | truncate(24, True, '') }}"
mariadb_enabled_on_startup: yes

# Databases.
mariadb_default_databases: []
mariadb_host_databases: []
mariadb_group_databases: []
#   - name: example
#     collation: utf8_general_ci
#     encoding: utf8
#     replicate: 1

# Users.
mariadb_default_users: []
mariadb_host_users: []
mariadb_group_users: []
#   - name: example
#     host: 127.0.0.1
#     password: secret
#     priv: *.*:USAGE

# Logging settings.
mariadb_log: ""
mariadb_log_error: /var/log/mysql.err
mariadb_syslog_tag: mysql

#mysql_repl_role: master
