version: '3'

services:

### ubuntu Server Container ##################################

    ubuntu:
      image: ubuntu:16.04
      ports:
          - "2221:22"
      container_name: server_01

### centos Server Container ##################################

    centos:
      image: centos:7
      ports:
          - "2222:22"
      container_name: server_01
