version: '3'

services:

### ubuntu Control Container ##################################

    control:
        image:
            jerichen/control-node-ubuntu:latest
        volumes:          
            - ${CONTROL_NODE_UBUNTU_LOG_PATH}:/var/log
        ports:
            - "2221:22"
        container_name: client

### ubuntu Managed Container ##################################

    ubuntu:
        image: 
            jerichen/managed-node-ubuntu:latest
        volumes:          
            - ${MANAGED_NODE_UBUNTU_LOG_PATH}:/var/log
        ports:
          - "2222:22"
        container_name: server01

## centos Managed Container ##################################
    
    # centos:
    #     image: 
    #         jerichen/managed-node-centos:latest
    #     ports:
    #       - "2223:22"
    #     container_name: server02
