version: '3'

services:

    ansible_ubuntu:
        build: 
            context: ./client
        ports:
            - "2222:22"
        container_name: client

### ubuntu Server Container ##################################

    ubuntu:
        build: 
            context: ./server_01
        ports:
          - "2221:22"
        container_name: server_01

### centos Server Container ##################################
    
    # centos:
    #     build: 
    #         context: ./server_02
    #     ports:
    #       - "2222:22"
    #     container_name: server_02
