version: '3'

services:

    # client:
    #     build: 
    #         context: ./dir
    #         dockerfile: Dockerfile-ansible-ubuntu
    #     ports:
    #         - "2222:22"

### ubuntu Server Container ##################################

    ubuntu:
        image: rastasheep/ubuntu-sshd:14.04
        ports:
          - "49154:22"
        container_name: server_01

### centos Server Container ##################################

    #centos:
      #image: centos:7
      #ports:
          #- "2222:22"
      #container_name: server_01
