version: '3'

services:

### ubuntu Control Container ##################################

    # control:
    #     build: 
    #         context: ./control-node-ubuntu
    #     ports:
    #         - "2222:22"
    #     container_name: client

### ubuntu Managed Container ##################################

    # ubuntu:
    #     build: 
    #         context: ./managed-node-centos
    #     ports:
    #       - "2221:22"
    #     container_name: server01

## centos Managed Container ##################################
    
    centos:
        build: 
            context: ./managed-node-centos
        ports:
          - "2222:22"
        container_name: server02
