version: '3'

services:

    control:
      image: jerichen/control-node-ubuntu:18.04
      volumes:
        - ${CONTROL_NODE_UBUNTU_LOG_PATH}:/var/log
        - ${CONTROL_DEV_PATH}:/root/dev
      ports:
        - "${CONTROL_NODE_UBUNTU_SSH_PORT}:22"
      container_name: client

    ubuntu:
      image: jerichen/managed-node-ubuntu:18.04
      volumes:
        - ~/drupal/mount/var/log/nginx:/var/log/nginx
        - ~/drupal/mount/var/www:/var/www/html
        - ~/drupal/mount/etc/nginx/site-enabled:/etc/nginx/site-enabled
        - ~/drupal/mount/etc/nginx/ssl:/etc/nginx/ssl
      ports:
        - "${MANAGED_NODE_UBUNTU_SSH_PORT}:22"
        - "${MANAGED_NODE_UBUNTU_HTTP_PORT}:80"
        - "${MANAGED_NODE_UBUNTU_HTTPS_PORT}:443"
      depends_on:
        - mysql
      container_name: web01

  ## mysql Managed Container ##################################
    mysql:
      image: mysql:5.7
      command: --max_allowed_packet=256M
      restart: always
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - ~/drupal/mount/var/lib/mysql:/var/lib/mysql
      ports:
        - "${MYSQL_PORT}:3306"
      container_name: mysql