version: '3'

services:

### ubuntu Server Container ##################################

    server-01:
      image: ubuntu:16.04
      ports:
          - "2221:22"

### centos Server Container ##################################

    server-02:
      image: centos:7
      ports:
          - "2222:22"
