version: '3'

services:

### ubuntu Control Container ##################################

    control:
        image:
            jerichen/control-node-ubuntu:latest
        volumes:          
            - ${CONTROL_NODE_UBUNTU_LOG_PATH}:/var/log
            - ${CONTROL_DEV_PATH}:/root/dev
        ports:
            - "${CONTROL_NODE_UBUNTU_SSH_PORT}:22"
        container_name: client

### ubuntu Managed Container ##################################

    ubuntu:
        image: 
            jerichen/managed-node-ubuntu:latest
        volumes:          
            - ${MANAGED_NODE_UBUNTU_LOG_PATH}:/var/log
        ports:
          - "${MANAGED_NODE_UBUNTU_SSH_PORT}:22"
        container_name: server01

## centos Managed Container ##################################
    
    # centos:
    #     image: 
    #         jerichen/managed-node-centos:latest
    #     ports:
    #       - "3333:22"
    #     container_name: server02
