- name: ubuntu restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: ubuntu reload nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes

- name: ubuntu test nginx and restart
  command: nginx -t
  notify:
    - ubuntu restart nginx

- name: centos restart nginx
#  systemctl:
  systemd:
    name: nginx
    state: restarted
    enabled: yes