- name: set variables
  set_fact:
    roles_name: "{{ role_path|basename }}"

- name: APT system for installation
  include_tasks: use-apt.yml
  when: ansible_pkg_mgr == 'apt'

#- name: YUM system for installation
#  include_tasks: use-yum.yml
#  when: ansible_pkg_mgr == 'yum'

#- name: install php7.1
#  apt:
#    name=php{{ php.version }}-{{ item }}
#    state=latest
#  with_items:
#    "{{ php_packages }}"
#  when:
#    ansible_distribution == 'Ubuntu'
#
#- name: install php7.1
#  yum:
#    name=php{{ php.version }}-{{ item }}
#    state=latest
#  with_items:
#    "{{ php_packages }}"
#  when:
#    ansible_distribution == 'CentOS' and
#    ansible_distribution_major_version == '7'