- name: install php packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_nested:
    "{{ apt_php_packages }}"
  when:
    apt_php_packages is defined
  notify:
    - restarted php7-fpm