- name: Install requires package for apt module
  apt:
    name: python-apt
    state: latest

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: latest

- name: Add PHP7 ppa repository
  apt_repository:
    repo: "{{ ubuntu_php7_ppa_repo }}"
  when:
    - ansible_distribution|lower == "ubuntu"

- name: Update and upgrade apt packages
  apt:
    force_apt_get: yes
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

#- name: Install php packages
#  apt:
#    name: "{{ item }}"
#    state: latest
#  with_nested:
#    "{{ apt_php_packages }}"
#  when:
#    apt_php_packages is defined
#  notify:
#    - restarted php{{ apt_php_version }}-fpm