- name: Install requires package for apt module
  apt:
    name: python-apt
    state: latest

- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: latest

- name: Add repository for Ubuntu
  apt_repository:
    repo: "{{ ubuntu_php7_ppa_repo }}"
  when:
    ansible_distribution|lower == "ubuntu"

- name: Update and upgrade apt packages
  apt:
    force_apt_get: yes
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install php packages
  apt:
    name: "{{ item }}"
    state: latest
  with_nested:
    "{{ apt_php_packages }}"
  when:
    apt_php_packages is defined

#- name: Change www.conf
#  template:
#    src: "php-fpm/www.conf.j2"
#    dest: "/etc/php/7.1/fpm/pool.d/www.conf"
#    owner: "root"
#    group: "root"
#    mode: "0755"
#    backup: "yes"
#
#- name: Add local-php71.com.tw.conf
#  template:
#    src: "php-fpm/local-php71.com.tw.conf.j2"
#    dest: "/etc/php/7.1/fpm/pool.d/local-php71.com.tw.conf"
#    owner: "root"
#    group: "root"
#    mode: "0755"
#    backup: "yes"
#
#- name: Add local-php56.com.tw.conf
#  template:
#    src: "php-fpm/local-php56.com.tw.conf.j2"
#    dest: "/etc/php/7.1/fpm/pool.d/local-php56.com.tw.conf"
#    owner: "root"
#    group: "root"
#    mode: "0755"
#    backup: "yes"

- name: Force start of php7.1-fpm service.
  command: service php7.1-fpm start