- name: Install requires package for yum module
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libselinux-python
    - epel-release

#- name: Add repository for Centos7
#  yum_repository:
#    name: remi-php71
#    description: Remi's PHP 7.1 RPM repository for Enterprise Linux 7 - $basearch
#    mirrorlist: http://rpms.remirepo.net/enterprise/7/php71/mirror
#    enabled: yes
#    gpgcheck: 1
#    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
#  when:
#    ansible_distribution == 'CentOS' and
#    ansible_distribution_major_version == '7'

- name: Install remi repo
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: Install yum-utils packages
  yum:
    name: yum-utils
    state: present

- name: enable remi php71 repo
  shell: yum-config-manager --enable remi-php71

- name: Update all packages
  yum:
    name: "*"
    state: latest

- name: Install php packages
  yum:
    name: "{{ item }}"
    state: latest
  with_nested:
    "{{ yum_php_packages }}"
  when:
    yum_php_packages is defined
  notify: restarted php7.1-fpm on centos