- name: Install requires package for yum module
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libselinux-python
    - epel-release

- name: Install remi repo
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
  when:
    ansible_distribution == 'CentOS' and
    ansible_distribution_major_version == '7'

- name: Install yum-utils packages
  yum:
    name: yum-utils
    state: present

- name: enable remi php71 repo
  shell: yum-config-manager --enable remi-php71

- name: Install php packages
  yum:
    name: "{{ item }}"
    state: latest
  with_nested:
    "{{ yum_php_packages }}"
  when:
    yum_php_packages is defined
  notify: restarted php7.1-fpm on centos