- name: Check jenkins is not install
  stat:
    path: /usr/lib/jenkins/jenkins.war
  register: jenkins_war

- name: Install Java8 packages
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Add jenkins repository
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0644

- name: Add jenkins apt key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present

- name: Install jenkins
  yum:
    name: jenkins
    state: present
    update_cache: yes
  when: jenkins_war.stat.exists == False

#- name: Change jenkins config
#  lineinfile:
#    path: '/etc/sysconfig/jenkins'
#    regexp: '^JENKINS_ARGS=""'
#    line: 'JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --httpListenAddress=127.0.0.1"'
#    backup: yes

- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: Create nginx ssl directory
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode:  0755

- name: generate SSL_certificate
  command:
    openssl req -nodes -new -x509 -newkey rsa:2048 -keyout {{ nginx_ssl_certificate_key }} -out {{ nginx_ssl_certificate }} -subj "{{ nginx_ssl_certificate_subject }}" -days {{ nginx_ssl_certificate_days }}
  args:
    creates: "{{ nginx_ssl_certificate }}"

- name: Create nginx cert directory
  file:
    path: /etc/nginx/cert
    state: directory
    owner: root
    group: root
    mode:  0755

- name: generate SSL_dhparam
  command:
    openssl dhparam -dsaparam -out /etc/nginx/cert/dhparam.pem 2048
  args:
    creates: "{{ nginx_ssl_dhparam_certificate }}"

- name: Create sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled
    state: directory
    owner: root
    group: root
    mode:  0755

- name: copy nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: "0755"
    backup: "yes"

- name: copy jenkins.conf
  template:
    src: "jenkins.conf.j2"
    dest: "/etc/nginx/sites-enabled/jenkins.conf"
    owner: "root"
    group: "root"
    mode: "0755"
    backup: "yes"

# 如果不配置SELinux，透過nginx反向代理訪問，產生錯誤如 connect() to 127.0.0.1:8001 failed (13: Permission denied
- name: generate SSL_certificate
  command: setsebool -P httpd_can_network_connect 1

- name: restarted nginx on centos7
  service:
    name: nginx.service
    state: restarted
    enabled: yes

- name: restarted jenkins on centos7
  service:
    name: jenkins.service
    state: restarted
    enabled: yes

- name: debug host ip
  debug:
    msg: "{{ansible_host}}"

- name: Wait for Jenkins to restart
  wait_for:
    host: "{{ansible_host}}"
    port: "{{ansible_port}}"
    delay: 20
    timeout: 100

- name: Get init password jenkin
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: Output init password jenkins
  debug:
    var: result.stdout