- name: Test connectivity
  ping:
  register: result

- name: Print result
  debug:
    msg: "{{ result }}"

- name: set variables
  set_fact:
    roles_name: "{{ role_path|basename }}"

- name: APT system for installation
  include_tasks: use-apt.yml
  when: ansible_pkg_mgr == 'apt'

- name: YUM system for installation
  include_tasks: use-yum.yml
  when: ansible_pkg_mgr == 'yum'
