- name: restarted php{{ php_version }}-fpm
  service:
    name: php{{ php_version }}-fpm
    state: restarted
    enabled: yes

- name: reloaded php{{ php_version }}-fpm
  service:
    name: php{{ php_version }}-fpm
    state: reloaded
    enabled: yes