- name: Test connectivity
  ping:
  register: result

- name: Print result
  debug:
    msg: "{{ result }}"

- name: set variables
  set_fact:
    roles_name: "{{ role_path|basename }}"

- name: Update and upgrade apt packages
  apt:
    force_apt_get: yes
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Ubuntu install Ruby
  apt:
    name: ruby-full
  when: ansible_distribution == 'Ubuntu'

- name: Ubuntu install curl
  apt:
    name: curl
  when: ansible_distribution == 'Ubuntu'

- name: Ubuntu curl Node.js
  shell: "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -"
  when: ansible_distribution == 'Ubuntu'

- name: Ubuntu install nodejs
  apt:
    name: nodejs
  when: ansible_distribution == 'Ubuntu'

- name: CentOS install git
  yum:
    name: git
  when:
    ansible_distribution == 'CentOS' and
    ansible_distribution_major_version == '7'