- name: Install requires package for yum module
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - libselinux-python
  - epel-release

- name: Install remi repo
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present
  when:
    ansible_distribution == 'CentOS' and
    ansible_distribution_major_version == '7'

- name: Install yum-utils packages
  yum:
    name: yum-utils
    state: present

- name: enable remi redis repo
  shell: yum-config-manager --enable rhel-server-rhscl-7-rpms

- name: Update all packages
  yum:
    name: "*"
    state: latest

- name: Install Redis server
  yum:
    name: redis
    state: present

- name: Ensure Redis Configuration
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restarted redis

