- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: latest

- name: Add repository for Ubuntu
  apt_repository:
    repo: "{{ ubuntu_java_ppa_repo }}"
  when:
    ansible_distribution|lower == "ubuntu"

- name: Update and upgrade apt packages
  apt:
    force_apt_get: yes
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: Install Java8 packages
  apt:
    name: "{{ item }}"
    state: latest
  with_nested:
    "{{ apt_java_packages }}"
  when:
    apt_java_packages is defined

- name: Add Elasticsearch apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/6.x/apt stable main'
    state: present

- name: Install Logstash
  apt:
    name: logstash
    state: present

- name: create an init.d Logstash
  command: /usr/share/logstash/bin/system-install /etc/logstash/startup.options sysv

- name: Change kibana.yml
  template:
    src: "logstash.yml.j2"
    dest: "/etc/logstash/logstash.yml"
    owner: root
    mode: 0644
  notify:
    - restarted logstash on ubuntu

#- name: trigger logstash restart on Ubuntu
#  debug:
#    msg: "trigger logstash restart on Ubuntu"
#  when:
#    ansible_distribution == 'Ubuntu'
#  notify:
#    - restarted logstash on ubuntu
#  changed_when: true
