# ubuntu
- name: restarted nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: reloaded nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes

- name: ubuntu test nginx and restart
  command: nginx -t
  notify:
    - ubuntu restart nginx

# centos
- name: restarted nginx on centos
  service:
    name: nginx.service
    state: restarted
    enabled: yes