- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: latest

- name: Add repository for Ubuntu
  apt_repository:
    repo: "{{ oracle_java_apt_repository }}"
    update_cache: yes
    state: present
  when:
    ansible_distribution|lower == "ubuntu"

- name: debian | set license as accepted
  debconf:
    name: "{{ oracle_java_deb_package }}"
    question: "{{ oracle_java_license_version }}"
    value: 'true'
    vtype: 'select'

- name: Install Java 13 packages
  apt:
    name:
      - oracle-java13-installer
      - oracle-java13-set-default
    state: latest
#    cache_valid_time: "{{ oracle_java_cache_valid_time }}"
#    update_cache: yes
    autoclean: yes

- name: Add Elasticsearch apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present

- name: Install Kibana
  apt:
    name: kibana
    state: present
  notify:
    - restarted kibana on ubuntu

- name: Change kibana.yml
  template:
    src: "kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"
    owner: root
    mode: 0644
  notify:
    - restarted kibana on ubuntu
