# root
ansible_root: "{{ inventory_dir | dirname }}"

# playbook
ansible_playbook_root: "{{ ansible_root }}/playbook"

# test debug
inventory_group_var: "inventory group var"

website: "local-example.com.tw"
php_71_fpm: "php7.1-fpm"
apt_php_version: "php7.1"
yum_php_version: "php71w"