# root
ansible_root: "{{ inventory_dir | dirname }}"

# playbook
ansible_playbook_root: "{{ ansible_root }}/playbook"

# test debug
inventory_group_var: "inventory group var example"

hosts_name: "dev"
website: "laravel-www.example.com"
php_71_fpm: "php7.1-fpm"
php_72_fpm: "php7.2-fpm"
apt_php71_version: "php7.1"
apt_php72_version: "php7.2"
yum_php_version: "php"

variable_host: "local"