# task 1
- name: test connection
  ping:
  register: message

# task 2
- name: print debug message
  debug:
    msg: "{{ message }}"

# task 3
- name: debug
  debug:
    msg: 
      - "{{ foo }}"

- name: composer create-project laravel
  composer:
    command: create-project
    arguments: '--prefer-dist laravel/laravel {{ web_site }}'
    working_dir: /var/www/html
    prefer_dist: yes

