# test task 1
- name: test connection
  ping:
  register: message

# test task 2
- name: print debug message
  debug:
    msg: "{{ message }}"

# test task 3
- name: debug
  debug:
    msg:
      "{{ inventory_group_var }}"

# test debug
- debug: var=website

# create new laravel website
- name: check website not install
  stat:
    path: "/var/www/html/{{ website }}"
  register: laravel_path

- name: composer create-project laravel
  composer:
    command: create-project
    arguments: '--prefer-dist laravel/laravel {{ website }}'
    working_dir: /var/www/html
    prefer_dist: yes
  when: laravel_path.stat.exists == False

- name: create sites-enabled config file
  template:
    src: 'templates/{{ php_version }}.conf.j2'
    dest: "/etc/nginx/sites-enabled/{{ website }}.conf"

- name: Change Storage Permission
  file:
    path: "/var/www/html/{{ website }}/storage/"
    mode: 0777
    recurse: yes

- name: ubuntu restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
