# task 1
- name: test connection
  ping:
  register: message

# task 2
- name: print debug message
  debug:
    msg: "{{ message }}"

# task 3
- name: debug
  debug:
    msg:
      "{{ inventory_group_var }}"

# test debug
- debug: var=website

# create new laravel website
- name: composer create-project laravel
  composer:
    command: create-project
    arguments: '--prefer-dist laravel/laravel {{ website }}'
    working_dir: /var/www/html
    prefer_dist: yes

- name: create sites-enabled config file
  template:
    src: 'templates/php71.conf.j2'
    dest: "/etc/nginx/sites-enabled/{{ website }}.conf"
