- name: set variables
  set_fact:
    roles_name: "{{ role_path|basename }}"

- name: Copy bashrc to master
  template:
    src: "bashrc.j2"
    dest: ".bashrc"
    owner: "root"
    group: "root"
    mode: "0755"
    backup: "yes"

- name: Copy bashrc to root
  template:
    src: "bashrc.j2"
    dest: "/root/.bashrc"
    owner: "root"
    group: "root"
    mode: "0755"
    backup: "yes"